language: node_js
dist: trusty
sudo: required
node_js: stable

install:
  - npm install -g bower purescript pulp
  - npm install -g rxjs snabbdom
  - npm install -g codecov

before_script:
  - cd Aula3

script:
  - bower install
  - pulp test
  - codecov
