language: node_js
dist: trusty
sudo: required
node_js: stable

install:
  - npm install -g bower purescript pulp
  - npm install rxjs snabbdom
  - bower install

after-script:
  - cd site
  
script:
  - pulp test

#after_success:
#- >-
#  test $TRAVIS_TAG &&
#  echo $GITHUB_TOKEN | pulp login &&
#  echo y | pulp publish --no-push
